package com.rhc.drools.example
import com.rhc.drools.example.persistence.Name;

rule "Sal's myName"
when
	$sal : Name(firstName == "Sal", lastName != "Elrahal")
then
	$sal.setLastName("Elrahal");
end

rule "Sam's myName"
when
	$sal : Name(firstName == "Sam", lastName != "Rang")
then
	$sal.setLastName("Rang");
end

rule "Everybody else"
when
	$otherName : Name(firstName != "Sal")
then
    $otherName.setFirstName("Sam");
end


